name: my_noti
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  firebase_analytics: ^10.4.3
  firebase_core: ^2.14.0
  firebase_messaging: ^14.6.3
  flutter:
    sdk: flutter
  flutter_local_notifications: ^15.1.0+1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
